hostname: openvas.example.com

psgvm:
  image:
    repository: registry.community.greenbone.net/community/pg-gvm
    tag: stable
ospd:
  image:
    repository: registry.community.greenbone.net/community/ospd-openvas
    tag: edge

#  4  Errors.
#  8  Critical situation.
# 16  Warnings.
# 32  Messages.
# 64  Information.
#128  Debug.  (Lots of output.)
logLevel: 16

gsa:
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 200Mi

gvmTools:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 150Mi

openvas:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 150m
      memory: 150Mi

openvasd:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 1
      memory: 500Mi

ospdOpenvas:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 2
      memory: 2Gi

pgGvm:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

redisServer:
  resources:
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: 1
      memory: 500Mi

gvmd:
  env:
    USER: "admin"
#    PASSWORD: "<password>"
#    MTA_HOST: "smtp.gmail.com"
#    MTA_PORT: 587
#    MTA_TLS: "on"
#    MTA_STARTTLS: "on"
#    MTA_AUTH: "on"
#    MTA_USER: "<username>"
#    MTA_FROM: "<username>@gmail.com"
#  existingSecret: "gvmd-secrets"
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 1
      memory: 500Mi

ingress:
  enabled: true 
  annotations: {}
  path: /
  hosts:
    - host: openvas.example.com
  
  # tls:
  #   - secretName: tls-secret-name
  #     hosts:
  #       - openvas.example.com

fullnameOverride: ""
nameOverride: ""
namespaceOverride: ""

persistence:
  gvmd:
    storageClass: "" # default
    accessMode: ReadWriteOnce
    size: 25Gi
  openvas:
    storageClass: "" # default
    accessMode: ReadWriteOnce
    size: 1Gi
  psql:
    storageClass: "" # default
    accessMode: ReadWriteOnce
    size: 50Gi

serviceAccount:
  create: false
  annotations: {}
  name: "openvas-serviceaccount"

maintenance:
  schedule: "0 18 * * 6"

podAnnotations: {}

podSecurityContext: 
  runAsUser: 0

securityContext:
  fsGroup: 0
  runAsUser: 0

service:
  type: ClusterIP

readinessProbe:
  # failureThreshold: 3
  # httpGet:
  #   path: /health
  #   port: 80
  #   scheme: HTTP
  # initialDelaySeconds: 5
  # periodSeconds: 2
  # successThreshold: 2
  # timeoutSeconds: 2

livenessProbe:
  # failureThreshold: 3
  # httpGet:
  #   path: /health
  #   port: 80
  #   scheme: HTTP
  # initialDelaySeconds: 5
  # periodSeconds: 2
  # successThreshold: 1
  # timeoutSeconds: 2

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []
