apiVersion: v1
entries:
  openvas:
  - apiVersion: v2
    appVersion: "22.04"
    created: "2025-05-15T18:34:04.282548421+05:00"
    description: greenbone openvas
    digest: 053c528554239a89c497a351c8d2c1a25468e1cf87ab24bd4fb9bfe3b488e579
    name: openvas
    type: application
    urls:
    - https://nietxan.github.io/greenbone-community-edition-helm/charts/openvas-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: "22.04"
    created: "2025-05-15T18:34:04.28074799+05:00"
    description: greenbone openvas
    digest: 8dbee6b7e666ce56144205b68eb86cd61482c75109b33605779cefa25920ad58
    name: openvas
    type: application
    urls:
    - https://nietxan.github.io/greenbone-community-edition-helm/charts/openvas-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: "22.04"
    created: "2025-05-15T18:34:04.277372314+05:00"
    description: greenbone openvas
    digest: 87414e5133196dfc74ce28723715fde1a86302bb2f1051881e26d4a0ae88dec2
    name: openvas
    type: application
    urls:
    - https://nietxan.github.io/greenbone-community-edition-helm/charts/openvas-1.0.0.tgz
    version: 1.0.0
generated: "2025-05-15T18:34:04.273408819+05:00"
