apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvas.fullname" . }}
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "openvas.selectorLabels" . | nindent 6 }}
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openvas.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      initContainers:
        - name: pg-init
          image: {{ .Values.psgvm.image.repository }}:{{ .Values.psgvm.image.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "/init-scripts/init-postgres.sh"]
          volumeMounts:
            - name: psql-storage
              mountPath: /mnt/postgresql
            - name: init-scripts
              mountPath: /init-scripts
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: notus-data
          image: registry.community.greenbone.net/community/notus-data
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /mnt
              subPath: notus-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: scap-data
          image: registry.community.greenbone.net/community/scap-data
          imagePullPolicy: Always
          volumeMounts:
            - name: gvmd-storage
              mountPath: /mnt
              subPath: scap-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: cert-bund-data
          image: registry.community.greenbone.net/community/cert-bund-data
          imagePullPolicy: Always
          volumeMounts:
            - name: gvmd-storage
              mountPath: /mnt
              subPath: cert-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: dfn-cert-data
          image: registry.community.greenbone.net/community/dfn-cert-data
          imagePullPolicy: Always
          volumeMounts:
            - name: gvmd-storage
              mountPath: /mnt
              subPath: cert-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: data-objects
          image: registry.community.greenbone.net/community/data-objects
          imagePullPolicy: Always
	  env:
	    - name: FEED_RELEASE
	      value: "24.10"
          volumeMounts:
            - name: gvmd-storage
              mountPath: /mnt
              subPath: data-objects/gvmd
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: report-formats
          image: registry.community.greenbone.net/community/report-formats
          imagePullPolicy: Always
	  env:
	    - name: FEED_RELEASE
	      value: "24.10"
          volumeMounts:
            - name: gvmd-storage
              mountPath: /mnt
              subPath: data-objects/gvmd
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: gpg-data
          image: registry.community.greenbone.net/community/gpg-data
          imagePullPolicy: Always
          volumeMounts:
            - name: openvas-storage
              mountPath: /mnt
              subPath: gnupg/gpg-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: vulnerability-tests
          image: registry.community.greenbone.net/community/vulnerability-tests
          imagePullPolicy: Always
          env:
            - name: STORAGE_PATH
              value: "/var/lib/openvas/22.04/vt-data/nasl"
	    - name: FEED_RELEASE
	      value: "24.10"
          volumeMounts:
            - name: shared-storage
              mountPath: /mnt
              subPath: vt-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

        - name: configure-openvas
          image: registry.community.greenbone.net/community/openvas-scanner:stable
          imagePullPolicy: Always
          volumeMounts:
            - name: openvas-storage
              mountPath: /mnt
            - name: shared-storage
              mountPath: /var/log/openvas
              subPath: openvas-log-data
          command: ["/bin/sh", "-c", "printf \"table_driven_lsc = yes\nopenvasd_server = http://openvasd:80\n\" > /mnt/openvas.conf && sed \"s/127/{{ .Values.logLevel }}/\" /etc/openvas/openvas_log.conf | sed 's/gvm/openvas/' > /mnt/openvas_log.conf && chmod 644 /mnt/openvas.conf && chmod 644 /mnt/openvas_log.conf && touch /var/log/openvas/openvas.log && chmod 666 /var/log/openvas/openvas.log"]
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

      containers:
        - name: redis-server
          image: registry.community.greenbone.net/community/redis-server
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /run/redis
              subPath: redis-socket
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.redisServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: pg-gvm
          image: {{ .Values.psgvm.image.repository }}:{{ .Values.psgvm.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: psql-storage
              mountPath: /var/lib/postgresql
            - name: shared-storage
              mountPath: /var/run/postgresql
              subPath: psql-socket
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R postgres:postgres /var/lib/postgresql"]
          {{- with .Values.pgGvm.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: gvmd
          image: registry.community.greenbone.net/community/gvmd:stable
          imagePullPolicy: Always
          volumeMounts:
            - name: gvmd-storage
              mountPath: /var/lib/gvm
            - name: shared-storage
              mountPath: /var/lib/openvas/plugins
              subPath: vt-data
            - name: psql-storage
              mountPath: /var/lib/postgresql
            - name: gvmd-socket
              mountPath: /run/gvmd
            - name: shared-storage
              mountPath: /run/ospd
              subPath: ospd-openvas-socket
            - name: shared-storage
              mountPath: /var/run/postgresql
              subPath: psql-socket
          {{- with .Values.gvmd }}
          {{- if .existingSecret }}
          envFrom:
          - secretRef:
              name: {{ .existingSecret }}
              optional: false
          {{- end }}

          {{- if .env }}
          env:
            {{- range $key, $value := .env }}
            {{- if $value }}
            - name: "{{ $key }}"
              value: |-
                {{ $value }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R gvmd:gvmd /run/gvmd; mkdir -p /var/lib/gvm/gvmd; chown -R gvmd:gvmd /var/lib/gvm"]
          {{- with .Values.gvmd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: gsa
          image: registry.community.greenbone.net/community/gsa:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 9392
              protocol: TCP
          volumeMounts:
            - name: gvmd-socket
              mountPath: /run/gvmd
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.gsa.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: openvas
          image: registry.community.greenbone.net/community/openvas-scanner:stable
          volumeMounts:
            - name: openvas-storage
              mountPath: /etc/openvas
            - name: shared-storage
              mountPath: /var/log/openvas
              subPath: openvas-log-data
          command: ["/bin/sh", "-c", "cat /etc/openvas/openvas.conf && tail -f /var/log/openvas/openvas.log"]
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.openvas.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: openvasd
          image: registry.community.greenbone.net/community/openvas-scanner:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 81
              protocol: TCP
          env:
            - name: OPENVASD_MODE
              value: "service_notus"
            - name: GNUPGHOME
              value: "/etc/openvas/gnupg"
            - name: LISTENING
              value: "0.0.0.0:81"
          volumeMounts:
            - name: openvas-storage
              mountPath: /etc/openvas
            - name: shared-storage
              mountPath: /var/log/openvas
              subPath: openvas-log-data
            - name: shared-storage
              mountPath: /var/lib/notus
              subPath: notus-data
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.openvasd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: ospd-openvas
          image: {{ .Values.ospd.image.repository }}:{{ .Values.ospd.image.tag }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          command: ["ospd-openvas", "-f", "--config", "/etc/gvm/ospd-openvas.conf", "--notus-feed-dir", "/var/lib/notus/advisories", "-m", "666"]
          volumeMounts:
            - name: shared-storage
              mountPath: /var/lib/openvas/plugins
              subPath: vt-data
            - name: shared-storage
              mountPath: /var/lib/notus
              subPath: notus-data
            - name: shared-storage
              mountPath: /run/ospd
              subPath: ospd-openvas-socket
            - name: shared-storage
              mountPath: /run/redis
              subPath: redis-socket
            - name: openvas-storage
              mountPath: /etc/openvas/
            - name: shared-storage
              mountPath: /var/log/openvas
              subPath: openvas-log-data
          {{- with .Values.ospdOpenvas.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: gvm-tools
          image: registry.community.greenbone.net/community/gvm-tools
          imagePullPolicy: Always
          volumeMounts:
            - name: gvmd-socket
              mountPath: /run/gvmd
            - name: shared-storage
              mountPath: /run/ospd
              subPath: ospd-openvas-socket
          args:
            - gosu gvm /bin/bash; while true; do sleep 600; done
          command:
            - sh
            - '-c'
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.gvmTools.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: shared-storage
          emptyDir: {}
        - name: gvmd-storage
          persistentVolumeClaim:
            claimName: gvmd-pvc
        - name: openvas-storage
          persistentVolumeClaim:
            claimName: openvas-pvc
        - name: psql-storage
          persistentVolumeClaim:
            claimName: psql-pvc
        - name: init-scripts
          configMap:
            name: init-scripts-config
            defaultMode: 0755
        - name: gvmd-socket
          emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
