---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gvmd-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.gvmd.storageClass }}
  storageClassName: {{ .Values.persistence.gvmd.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.gvmd.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gvmd.size | quote }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvas-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.openvas.storageClass }}
  storageClassName: {{ .Values.persistence.openvas.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.openvas.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.openvas.size | quote }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.psql.storageClass }}
  storageClassName: {{ .Values.persistence.psql.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.psql.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.psql.size | quote }}
